#!/usr/bin/env bash

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && exit 1

# List of supported devices
declare -ra SUPPORTED_DEVICES=(
  "bullhead"      # Nexus 5x
  "flounder"      # Nexus 9
  "angler"        # Nexus 6p
  "sailfish"      # Pixel
  "marlin"        # Pixel XL
  "walleye"       # Pixel 2
  "taimen"        # Pixel 2 XL
  "blueline"      # Pixel 3
  "crosshatch"    # Pixel 3 XL
  "sargo"	  # Pixel 3a
  "bonito"	  # Pixel 3a XL
)

# URLs to download factory images from
readonly NID_URL="https://google.com"
readonly GURL="https://developers.google.com/android/nexus/images"
readonly TOSURL="https://developers.google.com/profile/acknowledgeNotification"

# oatdump dependencies URLs as compiled from AOSP matching API levels
readonly L_OATDUMP_URL_API23='https://onedrive.live.com/download?cid=D1FAC8CC6BE2C2B0&resid=D1FAC8CC6BE2C2B0%21490&authkey=ACA4f4Zvs3Tb_SY'
readonly D_OATDUMP_URL_API23='https://onedrive.live.com/download?cid=D1FAC8CC6BE2C2B0&resid=D1FAC8CC6BE2C2B0%21493&authkey=AJ0rWu5Ci8tQNLY'
readonly L_OATDUMP_URL_API24='https://onedrive.live.com/download?cid=D1FAC8CC6BE2C2B0&resid=D1FAC8CC6BE2C2B0%21492&authkey=AE4uqwH-THvvkSQ'
readonly D_OATDUMP_URL_API24='https://onedrive.live.com/download?cid=D1FAC8CC6BE2C2B0&resid=D1FAC8CC6BE2C2B0%21491&authkey=AHvCaYwFBPYD4Fs'
readonly L_OATDUMP_URL_API25='https://onedrive.live.com/download?cid=D1FAC8CC6BE2C2B0&resid=D1FAC8CC6BE2C2B0%21503&authkey=AKDpBAzhzum6d7w'
readonly D_OATDUMP_URL_API25='https://onedrive.live.com/download?cid=D1FAC8CC6BE2C2B0&resid=D1FAC8CC6BE2C2B0%21504&authkey=AC5YFNSAZ31-W3o'
readonly L_OATDUMP_URL_API26='https://onedrive.live.com/download?cid=D1FAC8CC6BE2C2B0&resid=D1FAC8CC6BE2C2B0%21557&authkey=AG47qhXu164sYwc'
readonly D_OATDUMP_URL_API26='https://onedrive.live.com/download?cid=D1FAC8CC6BE2C2B0&resid=D1FAC8CC6BE2C2B0%21561&authkey=ABu-oqJbQDwQ-ZQ'
readonly L_OATDUMP_URL_API26_2='https://onedrive.live.com/download?cid=D1FAC8CC6BE2C2B0&resid=D1FAC8CC6BE2C2B0%21569&authkey=AG5PlexJR0YMLr0'
readonly D_OATDUMP_URL_API26_2='https://onedrive.live.com/download?cid=D1FAC8CC6BE2C2B0&resid=D1FAC8CC6BE2C2B0%21570&authkey=AJrlrh0v2GUvxow'
readonly L_OATDUMP_URL_API27='https://onedrive.live.com/download?cid=D1FAC8CC6BE2C2B0&resid=D1FAC8CC6BE2C2B0%21566&authkey=AKWYYxBfd7NMW_k'
readonly D_OATDUMP_URL_API27='https://onedrive.live.com/download?cid=D1FAC8CC6BE2C2B0&resid=D1FAC8CC6BE2C2B0%21567&authkey=AF-cDubRkZdjRxY'
readonly L_OATDUMP_URL_API28='https://onedrive.live.com/download?cid=D1FAC8CC6BE2C2B0&resid=D1FAC8CC6BE2C2B0%21574&authkey=ADSQA_DtfAmmk2c'
readonly D_OATDUMP_URL_API28='https://onedrive.live.com/download?cid=D1FAC8CC6BE2C2B0&resid=D1FAC8CC6BE2C2B0%21582&authkey=ABMMORAJ-GGjs2k'
readonly L_OATDUMP_URL_API29='https://onedrive.live.com/download?cid=D1FAC8CC6BE2C2B0&resid=D1FAC8CC6BE2C2B0%21574&authkey=ADSQA_DtfAmmk2c'
readonly D_OATDUMP_URL_API29='https://onedrive.live.com/download?cid=D1FAC8CC6BE2C2B0&resid=D1FAC8CC6BE2C2B0%21582&authkey=ABMMORAJ-GGjs2k'

readonly L_OATDUMP_API23_SIG='688f1c1f97e3b9eb32702c60ca05abbf313bc98a25334aa3ed4a108095162244'
readonly D_OATDUMP_API23_SIG='688f1c1f97e3b9eb32702c60ca05abbf313bc98a25334aa3ed4a108095162244'
readonly L_OATDUMP_API24_SIG='1f99e7d0f2894cfe52fb7f2a24d5076f217977cbb1a46fafdf5ea38b0a11adce'
readonly D_OATDUMP_API24_SIG='4a7f5614eb04d9bea85bfa05853523843f9cc80a64eab4c98efed2f70ed3d90e'
readonly L_OATDUMP_API25_SIG='8b8cd18f08afd00fc6bf33d5b7f5be4faab9f39849b258bade5d15c3e5f33ce8'
readonly D_OATDUMP_API25_SIG='97f26b40cdc1fb2b5e5babe7ff8c63b70e7d3a3ab8dee19b035bbb0fdfa5477e'
readonly L_OATDUMP_API26_SIG='d8c08fe0de637412086f8433b41808d7b58e92e7b7341fb9b4da44868d4b311b'
readonly D_OATDUMP_API26_SIG='6fd75110e85f0cc0316c5e7345ea4271d527aae2570552dc3c565177a4d6b743'
readonly L_OATDUMP_API26_2_SIG='22ab2469d32fbb1a4010528695c0c71ed1a3f7f5e956971b7f933e2df9b4f44a'
readonly D_OATDUMP_API26_2_SIG='03b603c09c1dfbdffa0518d39f5d7e5fcf04eac2e8b11bec27f2e4c36b162689'
readonly L_OATDUMP_API27_SIG='e8363ecbd6bc6bd4d3e86e5a59adfa77f62c3f765f4bb8d32706a538831357ac'
readonly D_OATDUMP_API27_SIG='2aaab14d1178845bf9d08b06b7afd3dfd845e882c9bf2c403593940a39ff3449'
readonly L_OATDUMP_API28_SIG='394a47491de4def3b825b22713f5ecfd8f16e00497f35213ffd83c2cc709384e'
readonly D_OATDUMP_API28_SIG='95ce6c296c5115861db3c876eb5bfd11cdc34deebace18462275368492c6ea87'
readonly L_OATDUMP_API29_SIG='394a47491de4def3b825b22713f5ecfd8f16e00497f35213ffd83c2cc709384e'
readonly D_OATDUMP_API29_SIG='95ce6c296c5115861db3c876eb5bfd11cdc34deebace18462275368492c6ea87'

# sub-directories that contain bytecode archives
declare -ra SUBDIRS_WITH_BC=("app" "framework" "priv-app" "overlay" "product")

# ART runtime files
declare -ra ART_FILE_EXTS=("odex" "oat" "art" "vdex")

# Files to skip from vendor partition when parsing factory images (for all configs)
declare -ra VENDOR_SKIP_FILES=(
  "build.prop"
  "compatibility_matrix.xml"
  "default.prop"
  "etc/NOTICE.xml.gz"
  "etc/wifi/wpa_supplicant.conf"
  "manifest.xml"
  "bin/toybox_vendor"
  "bin/toolbox"
  "bin/grep"
  "overlay/DisplayCutoutEmulationCorner/DisplayCutoutEmulationCornerOverlay.apk"
  "overlay/DisplayCutoutEmulationDouble/DisplayCutoutEmulationDoubleOverlay.apk"
  "overlay/DisplayCutoutEmulationTall/DisplayCutoutEmulationTallOverlay.apk"
  "overlay/DisplayCutoutNoCutout/NoCutoutOverlay.apk"
  "overlay/framework-res__auto_generated_rro.apk"
  "overlay/SysuiDarkTheme/SysuiDarkThemeOverlay.apk"
  "overlay/framework-res__auto_generated_rro_vendor.apk"
  "bin/awk"
  "bin/cplay"
  "bin/dumpsys"
  "bin/hostapd_cli"
  "bin/misc_writer"
  "bin/hw/android.hardware.atrace@1.0-service"
  "etc/init/android.hardware.atrace@1.0-service.rc"
  "etc/vintf/manifest/android.hardware.atrace@1.0-service.xml"
  "bin/hw/android.hardware.audio@2.0-service"
  "etc/init/android.hardware.audio@2.0-service.rc"
  "bin/hw/android.hardware.biometrics.fingerprint@2.1-service"
  "etc/init/android.hardware.biometrics.fingerprint@2.1-service.rc"
  "bin/hw/android.hardware.boot@1.0-service"
  "etc/init/android.hardware.boot@1.0-service.rc"
  "bin/hw/android.hardware.camera.provider@2.4-service"
  "etc/init/android.hardware.camera.provider@2.4-service.rc"
  "bin/hw/android.hardware.configstore@1.1-service"
  "etc/init/android.hardware.configstore@1.1-service.rc"
  "bin/hw/android.hardware.contexthub@1.0-service"
  "etc/init/android.hardware.contexthub@1.0-service.rc"
  "bin/hw/android.hardware.drm@1.0-service"
  "etc/init/android.hardware.drm@1.0-service.rc"
  "bin/hw/android.hardware.dumpstate@1.0-service.marlin"
  "etc/init/android.hardware.dumpstate@1.0-service.marlin.rc"
  "bin/hw/android.hardware.gatekeeper@1.0-service"
  "etc/init/android.hardware.gatekeeper@1.0-service.rc"
  "bin/hw/android.hardware.gnss@1.0-service"
  "etc/init/android.hardware.gnss@1.0-service.rc"
  "bin/hw/android.hardware.graphics.allocator@2.0-service"
  "etc/init/android.hardware.graphics.allocator@2.0-service.rc"
  "bin/hw/android.hardware.graphics.composer@2.1-service"
  "etc/init/android.hardware.graphics.composer@2.1-service.rc"
  "bin/hw/android.hardware.health@2.0-service.marlin"
  "etc/init/android.hardware.health@2.0-service.marlin.rc"
  "bin/hw/android.hardware.keymaster@3.0-service"
  "etc/init/android.hardware.keymaster@3.0-service.rc"
  "bin/hw/android.hardware.light@2.0-service"
  "etc/init/android.hardware.light@2.0-service.rc"
  "bin/hw/android.hardware.media.omx@1.0-service"
  "etc/init/android.hardware.media.omx@1.0-service.rc"
  "bin/hw/android.hardware.memtrack@1.0-service"
  "etc/init/android.hardware.memtrack@1.0-service.rc"
  "bin/hw/android.hardware.nfc@1.1-service"
  "etc/init/android.hardware.nfc@1.1-service.rc"
  "bin/hw/android.hardware.power@1.1-service.marlin"
  "etc/init/android.hardware.power@1.1-service.marlin.rc"
  "bin/hw/android.hardware.sensors@1.0-service"
  "etc/init/android.hardware.sensors@1.0-service.rc"
  "bin/hw/android.hardware.usb@1.1-service.marlin"
  "etc/init/android.hardware.usb@1.1-service.marlin.rc"
  "bin/hw/android.hardware.vibrator@1.0-service.marlin"
  "etc/init/android.hardware.vibrator@1.0-service.marlin.rc"
  "bin/hw/android.hardware.vr@1.0-service"
  "etc/init/android.hardware.vr@1.0-service.rc"
  "bin/hw/android.hardware.wifi@1.0-service"
  "etc/init/android.hardware.wifi@1.0-service.rc"
  "bin/hw/hostapd"
  "bin/hostapd_cli"
  "etc/init/hostapd.android.rc"
  "bin/hw/rild"
  "etc/init/rild.legacy.rc"
  "bin/hw/wpa_supplicant"
  "etc/wifi/wpa_supplicant_overlay.conf"
  "etc/wifi/wpa_supplicant.conf"
  "bin/logwrapper"
  "bin/mm-qcamera-app"
  "bin/nanoapp_cmd"
  "bin/nanotool"
  "bin/rmnetcli"
  "bin/init.foreground.sh"
  "bin/sha224sum"
  "bin/sh"
  "bin/init.qcom.devstart.sh"
  "bin/init.power.sh"
  "bin/sha1sum"
  "bin/sha256sum"
  "bin/sha384sum"
  "bin/init.mid.sh"
  "bin/unshare"
  "bin/sha512sum"
  "bin/init.radio.sh"
  "etc/mkshrc"
  "etc/mixer_paths_tasha_t50.xml"
  "etc/audio_platform_info_tasha_t50.xml"
  "etc/permissions/android.hardware.camera.flash-autofocus.xml"
  "etc/audio_platform_info_tasha.xml"
  "etc/selinux/precompiled_sepolicy.plat_sepolicy_and_mapping.sha256"
  "etc/selinux/precompiled_sepolicy.product_sepolicy_and_mapping.sha256"
  "etc/sound_trigger_mixer_paths_tasha_t50.xml"
  "bin/vndservice"
  "bin/vndservicemanager"
  "etc/init/vndservicemanager.rc"
  "etc/selinux/vndservice_contexts"
  "etc/fs_config_dirs"
  "etc/fs_config_files"
  "bin/groups"
  "etc/group"
  "etc/passwd"
  "etc/seccomp_policy/configstore@1.1.policy"
  "etc/selinux/plat_pub_versioned.cil"
  "etc/selinux/vendor_file_contexts"
  "etc/selinux/vendor_hwservice_contexts"
  "etc/selinux/vendor_mac_permissions.xml"
  "etc/selinux/vendor_property_contexts"
  "etc/selinux/vendor_seapp_contexts"
  "etc/selinux/vendor_sepolicy.cil"
  "etc/vintf/compatibility_matrix.xml"
  "etc/vintf/manifest.xml"
  "lib64/camera.device@1.0-impl.so"
  "lib/camera.device@1.0-impl.so"
  "lib64/camera.device@3.2-impl.so"
  "lib/camera.device@3.2-impl.so"
  "lib64/camera.device@3.3-impl.so"
  "lib/camera.device@3.3-impl.so"
  "lib64/camera.device@3.4-external-impl.so"
  "lib/camera.device@3.4-external-impl.so"
  "lib64/camera.device@3.4-impl.so"
  "lib/camera.device@3.4-impl.so"
  "lib64/hw/android.hardware.bluetooth.audio@2.0-impl.so"
  "lib/hw/android.hardware.bluetooth.audio@2.0-impl.so"
  "lib64/hw/android.hardware.camera.provider@2.4-impl.so"
  "lib/hw/android.hardware.camera.provider@2.4-impl.so"
  "lib/hw/android.hardware.drm@1.0-impl.so"
  "lib64/hw/android.hardware.graphics.mapper@2.0-impl-2.1.so"
  "lib/hw/android.hardware.graphics.mapper@2.0-impl-2.1.so"
  "lib64/hw/android.hardware.memtrack@1.0-impl.so"
  "lib/hw/android.hardware.memtrack@1.0-impl.so"
  "lib64/hw/android.hardware.renderscript@1.0-impl.so"
  "lib/hw/android.hardware.renderscript@1.0-impl.so"
  "lib64/hw/audio.bluetooth.default.so"
  "lib/hw/audio.bluetooth.default.so"
  "lib64/hw/audio.primary.default.so"
  "lib/hw/audio.primary.default.so"
  "lib64/hw/audio.primary.msm8996.so"
  "lib/hw/audio.primary.msm8996.so"
  "lib64/hw/audio.r_submix.default.so"
  "lib/hw/audio.r_submix.default.so"
  "lib64/hw/audio.usb.default.so"
  "lib/hw/audio.usb.default.so"
  "lib64/hw/bootctrl.msm8996.so"
  "lib/hw/bootctrl.msm8996.so"
  "lib/hw/camera.msm8996.so"
  "lib64/hw/gralloc.default.so"
  "lib/hw/gralloc.default.so"
  "lib64/hw/gralloc.msm8996.so"
  "lib/hw/gralloc.msm8996.so"
  "lib64/hw/hwcomposer.msm8996.so"
  "lib/hw/hwcomposer.msm8996.so"
  "lib64/hw/lights.marlin.so"
  "lib/hw/lights.marlin.so"
  "lib64/hw/lights.msm8996.so"
  "lib/hw/lights.msm8996.so"
  "lib64/hw/local_time.default.so"
  "lib/hw/local_time.default.so"
  "lib64/hw/memtrack.msm8996.so"
  "lib/hw/memtrack.msm8996.so"
  "lib64/hw/power.default.so"
  "lib/hw/power.default.so"
  "lib64/hw/sensors.marlin.so"
  "lib/hw/sensors.marlin.so"
  "lib64/hw/vibrator.default.so"
  "lib/hw/vibrator.default.so"
  "lib64/hw/vr.marlin.so"
  "lib/hw/vr.marlin.so"
  "lib64/libOmxCore.so"
  "lib/libOmxCore.so"
  "lib64/libOmxVdec.so"
  "lib/libOmxVdec.so"
  "lib64/libOmxVenc.so"
  "lib/libOmxVenc.so"
  "lib64/libalsautils.so"
  "lib/libalsautils.so"
  "lib/libavservices_minijail_vendor.so"
  "lib64/libbluetooth_audio_session.so"
  "lib/libbluetooth_audio_session.so"
  "lib64/libbt-vendor.so"
  "lib/libbt-vendor.so"
  "lib64/libc2dcolorconvert.so"
  "lib/libc2dcolorconvert.so"
  "lib64/libdynamic_sensor_ext.so"
  "lib/libdynamic_sensor_ext.so"
  "lib64/libeffects.so"
  "lib/libeffects.so"
  "lib64/libgptutils.so"
  "lib/libgptutils.so"
  "lib64/libhidparser.so"
  "lib/libhidparser.so"
  "lib64/libhubconnection.so"
  "lib/libhubconnection.so"
  "lib64/libmm-omxcore.so"
  "lib/libmm-omxcore.so"
  "lib/libmm-qcamera.so"
  "lib/libmmcamera_interface.so"
  "lib/libmmjpeg_interface.so"
  "lib64/libnbaio_mono.so"
  "lib/libnbaio_mono.so"
  "lib64/libqdMetaData.so"
  "lib/libqdMetaData.so"
  "lib64/libqdutils.so"
  "lib/libqdutils.so"
  "lib/libqomx_core.so"
  "lib64/libqservice.so"
  "lib/libqservice.so"
  "lib64/libreference-ril.so"
  "lib/libreference-ril.so"
  "lib64/libril.so"
  "lib/libril.so"
  "lib64/librilutils.so"
  "lib/librilutils.so"
  "lib64/librmnetctl.so"
  "lib/librmnetctl.so"
  "lib64/libsdmcore.so"
  "lib/libsdmcore.so"
  "lib64/libsdmutils.so"
  "lib/libsdmutils.so"
  "lib64/libsensorndkbridge.so"
  "lib/libsensorndkbridge.so"
  "lib64/libstagefrighthw.so"
  "lib/libstagefrighthw.so"
  "lib64/libtinycompress.so"
  "lib/libtinycompress.so"
  "lib64/libtinyxml.so"
  "lib/libtinyxml.so"
  "lib64/libwebrtc_audio_preprocessing.so"
  "lib/libwebrtc_audio_preprocessing.so"
  "lib64/libwpa_client.so"
  "lib/libwpa_client.so"
  "lib64/mediacas/libclearkeycasplugin.so"
  "lib/mediacas/libclearkeycasplugin.so"
  "lib64/mediadrm/libdrmclearkeyplugin.so"
  "lib/mediadrm/libdrmclearkeyplugin.so"
  "lib64/soundfx/libaudiopreprocessing.so"
  "lib/soundfx/libaudiopreprocessing.so"
  "lib64/soundfx/libbundlewrapper.so"
  "lib/soundfx/libbundlewrapper.so"
  "lib64/soundfx/libdownmix.so"
  "lib/soundfx/libdownmix.so"
  "lib64/soundfx/libdynproc.so"
  "lib/soundfx/libdynproc.so"
  "lib64/soundfx/libeffectproxy.so"
  "lib/soundfx/libeffectproxy.so"
  "lib64/soundfx/libldnhncr.so"
  "lib/soundfx/libldnhncr.so"
  "lib64/soundfx/libqcompostprocbundle.so"
  "lib/soundfx/libqcompostprocbundle.so"
  "lib64/soundfx/libqcomvisualizer.so"
  "lib/soundfx/libqcomvisualizer.so"
  "lib64/soundfx/libqcomvoiceprocessing.so"
  "lib/soundfx/libqcomvoiceprocessing.so"
  "lib64/soundfx/libqcomvoiceprocessingdescriptors.so"
  "lib/soundfx/libqcomvoiceprocessingdescriptors.so"
  "lib64/soundfx/libreverbwrapper.so"
  "lib/soundfx/libreverbwrapper.so"
  "lib64/soundfx/libvisualizer.so"
  "lib/soundfx/libvisualizer.so"
  "lib64/soundfx/libvolumelistener.so"
  "lib/soundfx/libvolumelistener.so"
  "lib64/ese_spi_nxp.so"
  "lib64/hw/android.hardware.boot@1.0-impl.so"
  "lib64/hw/android.hardware.contexthub@1.0-impl.nanohub.so"
  "lib64/hw/android.hardware.gatekeeper@1.0-impl.so"
  "lib64/hw/android.hardware.gnss@1.0-impl.so"
  "lib64/hw/android.hardware.graphics.allocator@2.0-impl.so"
  "lib64/hw/android.hardware.graphics.composer@2.1-impl.so"
  "lib64/hw/android.hardware.keymaster@3.0-impl.so"
  "lib64/hw/android.hardware.light@2.0-impl.so"
  "lib64/hw/android.hardware.sensors@1.0-impl.so"
  "lib64/hw/android.hardware.vr@1.0-impl.so"
  "lib64/libcld80211.so"
  "lib64/libhwc2on1adapter.so"
  "lib64/libhwc2onfbadapter.so"
  "lib64/libhwminijail.so"
  "lib64/libkeymaster3device.so"
  "lib64/libkeystore-engine-wifi-hidl.so"
  "lib64/libkeystore-wifi-hidl.so"
  "lib64/libwifi-hal.so"
  "lib64/nfc_nci_nxp.so"
  "odm/etc/build.prop"
  "bin/hw/android.hardware.cas@1.1-service"
  "bin/hw/android.hardware.drm@1.2-service.clearkey"
  "bin/hw/android.hardware.thermal@2.0-service.pixel"
  "etc/init/android.hardware.cas@1.1-service.rc"
  "etc/init/android.hardware.drm@1.2-service.clearkey.rc"
  "etc/init/android.hardware.thermal@2.0-service.pixel.rc"
  "etc/vintf/manifest/android.hardware.cas@1.1-service.xml"
  "etc/vintf/manifest/android.hardware.thermal@2.0-service.pixel.xml"
  "lib/android.hardware.camera.provider@2.4-external.so"
  "lib/android.hardware.camera.provider@2.4-legacy.so"
  "lib/camera.device@3.5-external-impl.so"
  "lib/camera.device@3.5-impl.so"
  "lib/hw/android.hardware.audio.effect@5.0-impl.so"
  "lib/hw/android.hardware.audio@5.0-impl.so"
  "lib/hw/android.hardware.soundtrigger@2.2-impl.so"
  "lib64/android.hardware.camera.provider@2.4-external.so"
  "lib64/android.hardware.camera.provider@2.4-legacy.so"
  "lib64/camera.device@3.5-external-impl.so"
  "lib64/camera.device@3.5-impl.so"
  "overlay/NfcNci__auto_generated_rro_vendor.apk"
  "overlay/SettingsProvider__auto_generated_rro_vendor.apk"
  "overlay/Bluetooth__auto_generated_rro_vendor.apk"
  "overlay/TeleService__auto_generated_rro_vendor.apk"
  "overlay/SystemUIGoogle__auto_generated_rro_vendor.apk"
)

# Files to skip from vendor partition when parsing factory images (for naked config only)
declare -ra VENDOR_SKIP_FILES_NAKED=(
  "etc/selinux/nonplat_file_contexts"
  "etc/selinux/nonplat_hwservice_contexts"
  "etc/selinux/nonplat_mac_permissions.xml"
  "etc/selinux/nonplat_property_contexts"
  "etc/selinux/nonplat_seapp_contexts"
  "etc/selinux/nonplat_sepolicy.cil"
  "etc/selinux/nonplat_service_contexts"
  "etc/selinux/plat_sepolicy_vers.txt"
  "etc/selinux/precompiled_sepolicy"
  "etc/selinux/precompiled_sepolicy.plat_and_mapping.sha256"
  "etc/selinux/vndservice_contexts"
)
